name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest 

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: "${{ secrets.AWS_REGION }}"
      TF_WORKING_DIR: "./terraform"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # ← Updated to v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  # ← Updated to v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-Terraform  # ← Optional but helpful

      # Add your Terraform workflow steps here
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan