name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest 

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: "${{ secrets.AWS_REGION }}"
      # REMOVED: TF_WORKING_DIR: ./terraform  ← Delete this line

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init    # ← No working-directory needed

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan  # ← Add -out=tfplan here

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        continue-on-error: true  # ← Ensures destroy runs even if apply fails completely
        run: terraform apply -auto-approve tfplan

      - name: Wait for testing (if successful)
        if: steps.apply.outcome == 'success'
        run: sleep 15m

      # ✅ CRITICAL: Always destroy if apply was attempted
      - name: Terraform Destroy (Success Path)
        if: always() && steps.apply.outcome == 'success'
        run: terraform destroy -auto-approve

      - name: Terraform Destroy (Failure Path)
        if: always() && steps.apply.outcome == 'failure'
        run: terraform destroy -auto-approve

    